config/routes.rb
Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  resources :events
  resources :places
  devise_for :users
  get 'welcome/index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  resources :fields

  root 'welcome#index'
end

app/models/field.rb
class Field < ApplicationRecord
    belongs_to :place
    has_many :events, dependent: :destroy
    default_scope -> { order(number: :asc) }
    validates :size, :presence => true,
                     :numericality => { :greater_than => 4, :less_than => 12 }
end

app/controllers/fields_controller.rb
class FieldsController < ApplicationController
  before_action :set_field, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, except: [:index, :show]

  # GET /fields
  # GET /fields.json
  def index
    if (current_user)
      @fields = Field.joins(:place).where("places.user_id = '%s'", current_user.id)
    else
      @fields = Field.all
    end
  end

  # GET /fields/1
  # GET /fields/1.json
  def show
    @event = Event.new
  end

  # GET /fields/new
  def new
    @field = Field.new
  end

  # GET /fields/1/edit
  def edit
  end

  # POST /fields
  # POST /fields.json
  def create
    @field = Field.new(field_params)
    @field.place_id = params[:place_id]
    respond_to do |format|
      if @field.save
        format.html { redirect_to @field, notice: 'Field was successfully created.' }
        format.json { render :show, status: :created, location: @field }
      else
        format.html { render :new }
        format.json { render json: @field.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /fields/1
  # PATCH/PUT /fields/1.json
  def update
    respond_to do |format|
      if @field.update(field_params)
        format.html { redirect_to @field, notice: 'Field was successfully updated.' }
        format.json { render :show, status: :ok, location: @field }
      else
        format.html { render :edit }
        format.json { render json: @field.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /fields/1
  # DELETE /fields/1.json
  def destroy
    @field.destroy
    respond_to do |format|
      format.html { redirect_to fields_url, notice: 'Field was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_field
      @field = Field.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def field_params
      params.require(:field).permit(:number, :size, :roofed, :illuminated)
    end
end

app/helpers/fields_helper.rb
module FieldsHelper
end

app/views/fields/_form.html.erb
<%= form_with(model: field, local: true) do |form| %>
  <% if field.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(field.errors.count, "error") %> prohibited this field from being saved:</h2>

      <ul>
      <% field.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
    
  <%= form.hidden_field :place_id, :value => params[:place_id] %>

  <div class="field">
    <%= form.label :number %>
    <%= form.number_field :number %>
  </div>

  <div class="field">
    <%= form.label :size %>
    <%= form.number_field :size %>
  </div>

  <div class="field">
    <%= form.label :roofed %>
    <%= form.check_box :roofed %>
  </div>

  <div class="field">
    <%= form.label :illuminated %>
    <%= form.check_box :illuminated %>
  </div>

  <div class="actions">
    <%= form.button  :submit , name: "place_id",value: params[:place_id]%>
  </div>
<% end %>

app/views/fields/edit.html.erb
<h1>Editing Field</h1>

<%= render 'form', field: @field %>

<%= link_to 'Show', @field %> |
<%= link_to 'Back', fields_path %>

app/views/fields/index.html.erb
<h1>Fields</h1>

<table>
  <thead>
    <tr>
      <th>Place</th>
      <th>Number</th>
      <th>Size</th>
      <th>Roofed</th>
      <th>Illuminated</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @fields.each do |field| %>
      <tr>
        <td><%= field.place_id %></td>
        <td><%= field.number %></td>
        <td><%= field.size %></td>
        <td><%= field.roofed %></td>
        <td><%= field.illuminated %></td>
        <td><%= link_to 'Show', field %></td>
        <% if user_signed_in? %>
          <td><%= link_to 'Edit', edit_field_path(field) %></td>
          <td><%= link_to 'Destroy', field, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        <% end %>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<% if user_signed_in? %>
  <%= link_to 'New Field', new_field_path %>
<% end %>

app/views/fields/new.html.erb
<h1>New Field</h1>

<%= render 'form', field: @field %>

<%= link_to 'Back', fields_path %>

app/views/fields/show.html.erb
<p>
  <strong>Number:</strong>
  <%= @field.number %>
</p>

<p>
  <strong>Size:</strong>
  <%= @field.size %>
</p>

<p>
  <strong>Roofed:</strong>
  <%= @field.roofed %>
</p>

<p>
  <strong>Illuminated:</strong>
  <%= @field.illuminated %>
</p>

<div id="calendar" data-turbolinks="false"></div>
<script >
   $('#calendar').fullCalendar({
    header: {
      left: 'prev,next today',
      center: 'title',
      right: '  '
    },
    defaultView: 'agendaWeek',
    slotDuration: '01:00:00',
    minTime: '06:00:00',
    maxTime: '23:00:00',
    businessHours: [ // specify an array instead
      {
        dow: [ 1, 2, 3 ], // Monday, Tuesday, Wednesday
        start: '08:00', // 8am
        end: '18:00' // 6pm
      },
      {
        dow: [ 4, 5 ], // Thursday, Friday
        start: '10:00', // 10am
        end: '16:00' // 4pm
      }
    ],
    selectable: true,
    selectHelper: true,
    editable: true,
    eventLimit: true,
    events: '/events.json',

    select: function(start, end) {
      $.getScript('/events/new', function() {});

      calendar.fullCalendar('unselect');
    },

    eventDrop: function(event, delta, revertFunc) {
      event_data = { 
        event: {
          id: event.id,
          start: event.start.format(),
          end: event.end.format()
        }
      };
      $.ajax({
          url: event.update_url,
          data: event_data,
          type: 'PATCH'
      });
    },
    
    eventClick: function(event, jsEvent, view) {
      $.getScript(event.edit_url, function() {});
    }
  });
</script>

<% if user_signed_in? %>
  <%= link_to 'Edit', edit_field_path(@field) %> |
<% end %>
<%= link_to 'Back', place_path(@field.place_id) %>


<div id="new_event" class="modal fade">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal"><span aria-hidden="true">&times;</span> <span class="sr-only">close</span></button>
                <h4>Add an Event</h4>
            </div>
            <div id="modalBody" class="modal-body">
              <%= render "events/form", :event => @event  %>
            </div>
            <div class="modal-footer">
                <button class="btn" data-dismiss="modal" aria-hidden="true">Cancel</button>
                <button type="submit" class="btn btn-primary" id="submitButton">Save</button>
            </div>
        </div>
    </div>
</div>

<div id="edit_event" class="modal fade">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal"><span aria-hidden="true">&times;</span> <span class="sr-only">close</span></button>
                <h4>Edit an Event</h4>
            </div>
            <div id="modalBody" class="modal-body">
              <%= render "events/form", :event => @event  %>
            </div>
            <div class="modal-footer">
                <button class="btn" data-dismiss="modal" aria-hidden="true">Cancel</button>
                <button type="submit" class="btn btn-primary" id="submitButton">Save</button>
            </div>
        </div>
    </div>
</div>