config/routes.rb
Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  resources :events
  resources :places
  devise_for :users
  get 'welcome/index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  resources :fields

  root 'welcome#index'
end

app/models/place.rb
class Place < ApplicationRecord
    has_many :fields, dependent: :destroy
    belongs_to :user
end

app/controllers/places_controller.rb
class PlacesController < ApplicationController
  before_action :set_place, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, except: [:index, :show]

  # GET /places
  # GET /places.json
  def index
    if (current_user)
      @places = Place.where(["user_id = '%s'", current_user.id])
    else
      @places = Place.all
    end
  end

  # GET /places/1
  # GET /places/1.json
  def show
    @place = Place.find(params[:id])
    @fields = @place.fields
  end

  # GET /places/new
  def new
    @place = Place.new
  end

  # GET /places/1/edit
  def edit
  end

  # POST /places
  # POST /places.json
  def create
    @place = Place.new(place_params)
    @place.user_id = current_user.id
    respond_to do |format|
      if @place.save
        format.html { redirect_to @place, notice: 'Place was successfully created.' }
        format.json { render :show, status: :created, location: @place }
      else
        format.html { render :new }
        format.json { render json: @place.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /places/1
  # PATCH/PUT /places/1.json
  def update
    respond_to do |format|
      if @place.update(place_params)
        format.html { redirect_to @place, notice: 'Place was successfully updated.' }
        format.json { render :show, status: :ok, location: @place }
      else
        format.html { render :edit }
        format.json { render json: @place.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /places/1
  # DELETE /places/1.json
  def destroy
    @place.destroy
    respond_to do |format|
      format.html { redirect_to places_url, notice: 'Place was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_place
      @place = Place.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def place_params
      params.require(:place).permit(:name, :address, :phone, :celphone, :email, :whatsapp)
    end
end

app/helpers/places_helper.rb
module PlacesHelper
end

app/views/places/_form.html.erb
<%= form_with(model: place, local: true) do |form| %>
  <% if place.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(place.errors.count, "error") %> prohibited this place from being saved:</h2>

      <ul>
      <% place.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :address %>
    <%= form.text_field :address %>
  </div>

  <div class="field">
    <%= form.label :phone %>
    <%= form.text_field :phone %>
  </div>

  <div class="field">
    <%= form.label :celphone %>
    <%= form.text_field :celphone %>
  </div>

  <div class="field">
    <%= form.label :email %>
    <%= form.text_field :email %>
  </div>

  <div class="field">
    <%= form.label :whatsapp %>
    <%= form.text_field :whatsapp %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/places/edit.html.erb
<h1>Editing Place</h1>

<%= render 'form', place: @place %>

<%= link_to 'Show', @place %> |
<%= link_to 'Back', places_path %>

app/views/places/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Places</h1>

<table>
  <thead>
    <tr>
      <th>User</th>
      <th>Name</th>
      <th>Address</th>
      <th>Phone</th>
      <th>Celphone</th>
      <th>Email</th>
      <th>Whatsapp</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @places.each do |place| %>
      <tr>
        <td><%= place.user_id %></td>
        <td><%= place.name %></td>
        <td><%= place.address %></td>
        <td><%= place.phone %></td>
        <td><%= place.celphone %></td>
        <td><%= place.email %></td>
        <td><%= place.whatsapp %></td>
        <td><%= link_to 'Show', place %></td>
        <% if user_signed_in? %>
          <td><%= link_to 'Edit', edit_place_path(place) %></td>
          <td><%= link_to 'Destroy', place, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        <% end %>
      </tr>
    <% end %>
  </tbody>
</table>

<br>
<% if user_signed_in? %>
  <%= link_to 'New Place', new_place_path %>
<% end %>

app/views/places/new.html.erb
<h1>New Place</h1>

<%= render 'form', place: @place %>

<%= link_to 'Back', places_path %>

app/views/places/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @place.name %>
</p>

<p>
  <strong>Address:</strong>
  <%= @place.address %>
</p>

<p>
  <strong>Phone:</strong>
  <%= @place.phone %>
</p>

<p>
  <strong>Celphone:</strong>
  <%= @place.celphone %>
</p>

<p>
  <strong>Email:</strong>
  <%= @place.email %>
</p>

<p>
  <strong>Whatsapp:</strong>
  <%= @place.whatsapp %>
</p>
<% if user_signed_in? %>
  <%= link_to 'Edit', edit_place_path(@place) %> |
<% end %>
<%= link_to 'Back', places_path %>

<h1>Fields</h1>

<table>
  <thead>
    <tr>
      <th>Place</th>
      <th>Number</th>
      <th>Size</th>
      <th>Roofed</th>
      <th>Illuminated</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @fields.each do |field| %>
      <tr>
        <td><%= field.place_id %></td>
        <td><%= field.number %></td>
        <td><%= field.size %></td>
        <td><%= field.roofed %></td>
        <td><%= field.illuminated %></td>
        <td><%= link_to 'Show', field %></td>
        <% if user_signed_in? %>
          <td><%= link_to 'Edit', edit_field_path(field) %></td>
          <td><%= link_to 'Destroy', field, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        <% end %>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<% if user_signed_in? %>
  <%= link_to 'New Field', new_field_path(:place_id => @place.id) %>
<% end %>